version: '3.7'
services:
  db:
    build: ./db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=schedule
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    networks: 
      - laba_net

  web:
    build: ./baseapp
    command: python manage.py runserver 0:8000
    volumes:
      - ./baseapp/:/usr/src/baseapp/
    ports:
      - 8000:8000
    env_file:
      - ./.dev.env
    depends_on:
      - db
    networks: 
      - laba_net

  ngrok:
    image: wernight/ngrok
    env_file: 
        - ./ngrok/.env
    ports:
      - 4040:4040
    networks: 
      - laba_net

volumes:
  postgres_data:

networks: 
  laba_net:
    name: laba_net