version: '3.7'
services:
  db:
    image: den1ss1mo/smart-scheduler_db:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: 
      - .prod.db.env
    networks: 
      - common

  web:
    image: den1ss1mo/smart-scheduler_web:latest
    command: gunicorn baseapp.wsgi:application --bind 0.0.0.0:8000
    restart: always
    volumes:
      - ./baseapp/:/usr/src/baseapp/
    expose:
      - 8000
    env_file:
      - ./.dev.env
    depends_on:
      - db
    networks: 
      - common

  ngrok:
    image: wernight/ngrok
    env_file: 
        - ./ngrok/.env
    expose:
      - 4040
    networks: 
      - common

  nginx:
    image: den1ss1mo/smart-scheduler_nginx:latest
    restart: always
    networks:
        - common
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:

networks: 
  common:
    name: common