version: '3.7'
services:
  db:
    build: ./db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=schedule
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
  web:
    build: ./baseapp
    command: python manage.py runserver 0:8080
    volumes:
      - ./baseapp/:/usr/src/baseapp/
    ports:
      - 8080:8080
    env_file:
      - ./.dev.env
    image: den1ss1mo/smart-schedule
    depends_on:
      - db
  ngrok:
    image: wernight/ngrok
    depends_on: 
        - web
    env_file: 
        - ./ngrok/.env
    ports:
      - 4040:4040
volumes:
  postgres_data: