# Generated by Django 3.2.2 on 2021-05-27 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20210527_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouplead',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot.studentgroup'),
        ),
        migrations.AlterField(
            model_name='grouplead',
            name='user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
