# Generated by Django 3.2.2 on 2021-05-28 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20210527_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='telegram_username',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
