# Generated by Django 3.2.2 on 2021-05-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_chat_telegram_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
