# Generated by Django 3.2.2 on 2021-05-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_employee_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='subgroup',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
