# Generated by Django 3.2.2 on 2021-05-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_lesson_subgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='zaoch',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
