# Generated by Django 3.2.2 on 2021-05-14 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleuser',
            name='date_of_birth',
        ),
    ]
