name: ci

on:
  push:
    branches: master

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: publish
        uses: pennsignals/publish_docker-compose@v0.1.0
        with:
          docker_compose: 'docker-compose.yml' # required
          repo_token: "${{ secrets.REPO_TOKEN }}"
