name: run_tests

on:
 push:
   tags:
     - '!refs/tags/*'
   branches:
     - '*'
jobs:
 run_tests:
   runs-on: [ubuntu-latest]
   steps:
  # Чекаутим код
 - uses: actions/checkout@master
   # Устанавливаем python нужной версии
 - uses: actions/setup-python@v1
   with:
     python-version: '3.8'
     architecture: 'x64'
 - name: Install requirements
   # Устанавливаем зависимости
   run: pip install -r baseapp/requirements.txt
 - name: Run tests
   run: pytest --cov=bot /baseapp > coverage.report
 - name: Tests report
   run: echo coverage.report && rm coverage.report 